name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: ../dbt_modules
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: table
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
vars:
  dbt_utils_dispatch_list:
  - airbyte_utils
  json_column: _airbyte_data
  models_to_source:
    local_1024_ab1: halo._airbyte_raw_local_1024
    local_1024_ab2: halo._airbyte_raw_local_1024
    local_1024_ab3: halo._airbyte_raw_local_1024
    local_1024: halo._airbyte_raw_local_1024
